version: "3.9"

services:
  # ======================
  # Banco relacional
  # ======================
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devcalc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - shared_data:/shared
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d devcalc"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ======================
  # Banco não relacional
  # ======================
  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - shared_data:/shared
    networks:
      - dev-network
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({ping: 1})' | mongosh localhost:27017/devcalc --quiet || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ======================
  # Container de teste
  # ======================
  test-box:
    image: busybox
    container_name: test-box
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    command: sh -c "sleep 3600" # mantém o container ativo
    volumes:
      - shared_data:/shared
    networks:
      - dev-network

# ======================
# Rede compartilhada
# ======================
networks:
  dev-network:
    driver: bridge

# ======================
# Volumes
# ======================
volumes:
  pg_data:
  mongo_data:
  shared_data:
